export const navLinks = [
  "home",
  "about",
  "products",
  "blog",
  "contact",
  "premium",
  "profile",
];

export const blogs = [
  {
    title: "Sun Shines Bright, The",
    desc: "Other superficial bite of breast",
    image: "http://dummyimage.com/161x100.png/ff4444/ffffff",
    date: "3/9/2024",
  },
  {
    title: "George Lopez: Tall, Dark & Chicano",
    desc: "Burns involving 20-29% of body surface",
    image: "http://dummyimage.com/226x100.png/5fa2dd/ffffff",
    date: "3/31/2023",
  },
  {
    title: "Five and Ten",
    desc: "Displ oblique fx shaft of l femr, 7thE",
    image: "http://dummyimage.com/117x100.png/5fa2dd/ffffff",
    date: "2/3/2024",
  },
  {
    title: "Crush, The (La cotta)",
    desc: "Fibrous dysplasia (monostotic), left ankle and foot",
    image: "http://dummyimage.com/180x100.png/dddddd/000000",
    date: "4/30/2023",
  },
  {
    title: "Wrestling Ernest Hemingway",
    desc: "Undrdose of pertussis vaccine, inc combin w pertuss, subs",
    image: "http://dummyimage.com/247x100.png/dddddd/000000",
    date: "6/22/2023",
  },
  {
    title: "Dust of Time, The",
    desc: "Osteophyte, unspecified wrist",
    image: "http://dummyimage.com/183x100.png/cc0000/ffffff",
    date: "12/22/2023",
  },
  {
    title: "Shock and Awe: The Story of Electricity",
    desc: "Other articular cartilage disorders, ankle and foot",
    image: "http://dummyimage.com/146x100.png/5fa2dd/ffffff",
    date: "11/3/2023",
  },
  {
    title: "Whole Wide World, The",
    desc: "Adverse effect of saline and osmotic laxatives, sequela",
    image: "http://dummyimage.com/162x100.png/ff4444/ffffff",
    date: "3/9/2024",
  },
  {
    title: "Through and Through (Na wylot)",
    desc: "Type 2 diabetes mellitus with other skin complications",
    image: "http://dummyimage.com/235x100.png/ff4444/ffffff",
    date: "2/25/2024",
  },
  {
    title: "Buona Sera, Mrs. Campbell",
    desc: "Encounter for surveillance of contraceptive pills",
    image: "http://dummyimage.com/206x100.png/ff4444/ffffff",
    date: "1/10/2024",
  },
  {
    title: "Playing for Keeps",
    desc: "Fracture of unspecified part of neck of femur",
    image: "http://dummyimage.com/212x100.png/ff4444/ffffff",
    date: "8/5/2023",
  },
  {
    title: "Sex: The Annabel Chong Story",
    desc: "Toxic effect of lead and its compounds, self-harm",
    image: "http://dummyimage.com/165x100.png/5fa2dd/ffffff",
    date: "6/5/2023",
  },
  {
    title: "Questioning Darwin",
    desc: "Nondisp fx of body of left talus, subs for fx w delay heal",
    image: "http://dummyimage.com/118x100.png/dddddd/000000",
    date: "12/31/2023",
  },
  {
    title: "Awakening, The",
    desc: "Rh incompat reaction due to transfuse of bld/bld prod, unsp",
    image: "http://dummyimage.com/103x100.png/dddddd/000000",
    date: "3/5/2024",
  },
  {
    title: "Chasing Christmas",
    desc: "Displaced spiral fracture of shaft of humerus, left arm",
    image: "http://dummyimage.com/218x100.png/dddddd/000000",
    date: "2/22/2024",
  },
  {
    title: "The Savior",
    desc: "Other chronic hematogenous osteomyelitis, radius and ulna",
    image: "http://dummyimage.com/244x100.png/ff4444/ffffff",
    date: "5/19/2023",
  },
  {
    title: "Scenesters, The",
    desc: "Alcoholic gastritis",
    image: "http://dummyimage.com/136x100.png/cc0000/ffffff",
    date: "1/31/2024",
  },
  {
    title: "Smurfs 2, The",
    desc: "Toxic effect of halogenated insecticides, self-harm, init",
    image: "http://dummyimage.com/109x100.png/dddddd/000000",
    date: "4/7/2023",
  },
  {
    title: "Wings (Krylya)",
    desc: "Open bite of abd wall, unsp q w penet perit cav, sequela",
    image: "http://dummyimage.com/102x100.png/cc0000/ffffff",
    date: "2/7/2024",
  },
  {
    title: "Afterschool",
    desc: "Toxic effect of chlorine gas, undetermined, subs encntr",
    image: "http://dummyimage.com/177x100.png/5fa2dd/ffffff",
    date: "9/29/2023",
  },
];
export const products = [
  {
    id: 1,
    title: "iPhone 9",
    description: "An apple mobile which is nothing like apple",
    price: 549,
    discountPercentage: 12.96,
    rating: 4.69,
    stock: 94,
    brand: "Apple",
    category: "smartphones",
    thumbnail: "https://cdn.dummyjson.com/product-images/1/thumbnail.jpg",
  },
  {
    id: 2,
    title: "iPhone X",
    description:
      "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
    price: 899,
    discountPercentage: 17.94,
    rating: 4.44,
    stock: 34,
    brand: "Apple",
    category: "smartphones",
    thumbnail: "https://cdn.dummyjson.com/product-images/2/thumbnail.jpg",
  },
  {
    id: 3,
    title: "Samsung Universe 9",
    description:
      "Samsung's new variant which goes beyond Galaxy to the Universe",
    price: 1249,
    discountPercentage: 15.46,
    rating: 4.09,
    stock: 36,
    brand: "Samsung",
    category: "smartphones",
    thumbnail: "https://cdn.dummyjson.com/product-images/3/thumbnail.jpg",
  },
  {
    id: 4,
    title: "OPPOF19",
    description: "OPPO F19 is officially announced on April 2021.",
    price: 280,
    discountPercentage: 17.91,
    rating: 4.3,
    stock: 123,
    brand: "OPPO",
    category: "smartphones",
    thumbnail: "https://cdn.dummyjson.com/product-images/4/thumbnail.jpg",
  },
];
